version: '3'

services:
  php:
    build:
      context: .
    ports:
    - 8000:8000
    environment:
      - MEILISEARCH_HOST=meilisearch:7700
      - MEILISEARCH_KEY=null
  meilisearch:
    image: getmeili/meilisearch:v0.11.0
    ports:
      - 7700:7700
    volumes:
      - ./data.ms:/data.ms
